# Data Manipulation Studio

For this studio, we will revisit the data set from our last studio. If you recall, California farmers were looking for advice on growing pumpkins. We will use the same [pumpkins dataset](https://www.kaggle.com/usda/a-year-of-pumpkin-prices) as provided by the U.S. Department of Agriculture. You may have to clean data in the process of data manipulation, so feel free to pull up your notebook from the last class's studio.

We will now be focusing our attention on a different region in the United States, the Northeast. When you open up the `dataset` folder, you will have 13 CSVs, including the San Francisco and Los Angeles data from the last lesson. The 13 CSVs are each a different terminal market in the United States.

A **terminal market** is a central site, often in a metropolitan area, that serves as an assembly and trading place for commodities. Terminal markets for agricultural commodities are usually at or near major transportation hubs. [Definition Source](https://en.wikipedia.org/wiki/Terminal_market#:~:text=A%20terminal%20market%20is%20a,or%20near%20major%20transportation%20hubs)

## Getting Started

Import the CSVs for each of the following cities: Baltimore, Boston, New York, and Philadelphia. Set up a dataframe for each city.

In [27]:
# Import the necessary libraries and CSVs. Make some dataframes!
import pandas as pd
import numpy as np
baltimore = pd.read_csv(r"/Users/bhushankini/Desktop/LaunchCode/data-analysis-projects/data-manipulation/studio/data-manipulation-studio/dataset/baltimore_9-24-2016_9-30-2017.csv")
boston = pd.read_csv(r"/Users/bhushankini/Desktop/LaunchCode/data-analysis-projects/data-manipulation/studio/data-manipulation-studio/dataset/boston_9-24-2016_9-30-2017.csv")
new_york = pd.read_csv(r"/Users/bhushankini/Desktop/LaunchCode/data-analysis-projects/data-manipulation/studio/data-manipulation-studio/dataset/new-york_9-24-2016_9-30-2017.csv")
philadelphia = pd.read_csv(r"/Users/bhushankini/Desktop/LaunchCode/data-analysis-projects/data-manipulation/studio/data-manipulation-studio/dataset/philadelphia_9-24-2016_9-30-2017.csv")

baltimore_df = pd.DataFrame(baltimore)
print(baltimore_df)

boston_df = pd.DataFrame(boston)
print(boston_df)

new_york_df = pd.DataFrame(new_york)
print(new_york_df)

philadelphia_df = pd.DataFrame(philadelphia)
print(philadelphia_df)

    Commodity Name  City Name  Type             Package      Variety  \
0         PUMPKINS  BALTIMORE   NaN        24 inch bins          NaN
1         PUMPKINS  BALTIMORE   NaN        24 inch bins          NaN
2         PUMPKINS  BALTIMORE   NaN        24 inch bins  HOWDEN TYPE
3         PUMPKINS  BALTIMORE   NaN        24 inch bins  HOWDEN TYPE
4         PUMPKINS  BALTIMORE   NaN        24 inch bins  HOWDEN TYPE
..             ...        ...   ...                 ...          ...
148       PUMPKINS  BALTIMORE   NaN  1/2 bushel cartons    MINIATURE
149       PUMPKINS  BALTIMORE   NaN  1/2 bushel cartons    MINIATURE
150       PUMPKINS  BALTIMORE   NaN  1/2 bushel cartons    MINIATURE
151       PUMPKINS  BALTIMORE   NaN  1/2 bushel cartons    MINIATURE
152       PUMPKINS  BALTIMORE   NaN  1/2 bushel cartons    MINIATURE

    Sub Variety  Grade        Date  Low Price  High Price  ...   Color  \
0           NaN    NaN  04/29/2017        270       280.0  ...     NaN
1           NaN    NaN  05/06/2017        270       280.0  ...     NaN
2           NaN    NaN  09/24/2016        160       160.0  ...     NaN
3           NaN    NaN  09/24/2016        160       160.0  ...     NaN
4           NaN    NaN  11/05/2016         90       100.0  ...     NaN
..          ...    ...         ...        ...         ...  ...     ...
148         NaN    NaN  09/30/2017         18        18.0  ...  ORANGE
149         NaN    NaN  09/30/2017         18        18.0  ...  ORANGE
150  ROUND TYPE    NaN  09/24/2016         15        15.0  ...     NaN
151  ROUND TYPE    NaN  10/01/2016         15        15.0  ...     NaN
152  ROUND TYPE    NaN  10/08/2016         15        15.0  ...     NaN

     Environment Unit of Sale  Quality Condition Appearance  Storage Crop  \
0            NaN          NaN      NaN       NaN        NaN      NaN  NaN
1            NaN          NaN      NaN       NaN        NaN      NaN  NaN
2            NaN          NaN      NaN       NaN        NaN      NaN  NaN
3            NaN          NaN      NaN       NaN        NaN      NaN  NaN
4            NaN          NaN      NaN       NaN        NaN      NaN  NaN
..           ...          ...      ...       ...        ...      ...  ...
148          NaN          NaN      NaN       NaN        NaN      NaN  NaN
149          NaN          NaN      NaN       NaN        NaN      NaN  NaN
150          NaN          NaN      NaN       NaN        NaN      NaN  NaN
151          NaN          NaN      NaN       NaN        NaN      NaN  NaN
152          NaN          NaN      NaN       NaN        NaN      NaN  NaN

     Repack  Trans Mode
0         E         NaN
1         E         NaN
2         N         NaN
3         N         NaN
4         N         NaN
..      ...         ...
148       N         NaN
149       N         NaN
150       N         NaN
151       N         NaN
152       N         NaN

[153 rows x 25 columns]
    Commodity Name City Name  Type             Package      Variety  \
0         PUMPKINS    BOSTON   NaN        36 inch bins  HOWDEN TYPE
1         PUMPKINS    BOSTON   NaN        36 inch bins  HOWDEN TYPE
2         PUMPKINS    BOSTON   NaN        36 inch bins  HOWDEN TYPE
3         PUMPKINS    BOSTON   NaN        36 inch bins  HOWDEN TYPE
4         PUMPKINS    BOSTON   NaN        36 inch bins  HOWDEN TYPE
..             ...       ...   ...                 ...          ...
347       PUMPKINS    BOSTON   NaN  1/2 bushel cartons    MINIATURE
348       PUMPKINS    BOSTON   NaN  1/2 bushel cartons    MINIATURE
349       PUMPKINS    BOSTON   NaN  1/2 bushel cartons    MINIATURE
350       PUMPKINS    BOSTON   NaN  1/2 bushel cartons    MINIATURE
351       PUMPKINS    BOSTON   NaN  1/2 bushel cartons    MINIATURE

    Sub Variety  Grade        Date  Low Price  High Price  ...   Color  \
0           NaN    NaN  09/24/2016        160         200  ...  ORANGE
1           NaN    NaN  09/24/2016        160         200  ...  ORANGE
2           NaN    NaN  09/24/2016        160         200  ...  ORANGE
3           NaN    NaN  09/24/2016        160         200  ...  ORANGE
4           NaN    NaN  09/24/2016        160         180  ...  ORANGE
..          ...    ...         ...        ...         ...  ...     ...
347  ROUND TYPE    NaN  10/22/2016         15          18  ...  ORANGE
348  ROUND TYPE    NaN  10/29/2016         15          18  ...   WHITE
349  ROUND TYPE    NaN  10/29/2016         15          18  ...  ORANGE
350  ROUND TYPE    NaN  11/05/2016         15          18  ...   WHITE
351  ROUND TYPE    NaN  11/05/2016         15          18  ...  ORANGE

     Environment Unit of Sale Quality Condition Appearance  Storage Crop  \
0            NaN          NaN     NaN       NaN        NaN      NaN  NaN
1            NaN          NaN     NaN       NaN        NaN      NaN  NaN
2            NaN          NaN     NaN       NaN        NaN      NaN  NaN
3            NaN          NaN     NaN       NaN        NaN      NaN  NaN
4            NaN          NaN     NaN       NaN        NaN      NaN  NaN
..           ...          ...     ...       ...        ...      ...  ...
347          NaN          NaN     NaN       NaN        NaN      NaN  NaN
348          NaN          NaN     NaN       NaN        NaN      NaN  NaN
349          NaN          NaN     NaN       NaN        NaN      NaN  NaN
350          NaN          NaN     NaN       NaN        NaN      NaN  NaN
351          NaN          NaN     NaN       NaN        NaN      NaN  NaN

     Repack  Trans Mode
0         N         NaN
1         N         NaN
2         N         NaN
3         N         NaN
4         N         NaN
..      ...         ...
347       N         NaN
348       N         NaN
349       N         NaN
350       N         NaN
351       N         NaN

[352 rows x 25 columns]
    Commodity Name City Name  Type              Package      Variety  \
0         PUMPKINS  NEW YORK   NaN         36 inch bins  HOWDEN TYPE
1         PUMPKINS  NEW YORK   NaN         36 inch bins  HOWDEN TYPE
2         PUMPKINS  NEW YORK   NaN         36 inch bins  HOWDEN TYPE
3         PUMPKINS  NEW YORK   NaN         36 inch bins  HOWDEN TYPE
4         PUMPKINS  NEW YORK   NaN         36 inch bins  HOWDEN TYPE
..             ...       ...   ...                  ...          ...
107       PUMPKINS  NEW YORK   NaN       bushel cartons    MINIATURE
108       PUMPKINS  NEW YORK   NaN  1 1/9 bushel crates    MINIATURE
109       PUMPKINS  NEW YORK   NaN  1 1/9 bushel crates    MINIATURE
110       PUMPKINS  NEW YORK   NaN  1 1/9 bushel crates    MINIATURE
111       PUMPKINS  NEW YORK   NaN  1 1/9 bushel crates    MINIATURE

    Sub Variety  Grade        Date  Low Price  High Price  ...  Color  \
0           NaN    NaN  09/24/2016        150         170  ...    NaN
1           NaN    NaN  09/24/2016        150         170  ...    NaN
2           NaN    NaN  09/24/2016        130         150  ...    NaN
3           NaN    NaN  09/24/2016        130         150  ...    NaN
4           NaN    NaN  09/24/2016        120         140  ...    NaN
..          ...    ...         ...        ...         ...  ...    ...
107         NaN    NaN  09/09/2017         32          32  ...    NaN
108  ROUND TYPE    NaN  10/08/2016         18          18  ...    NaN
109  ROUND TYPE    NaN  10/08/2016         18          18  ...    NaN
110  ROUND TYPE    NaN  10/15/2016         18          18  ...    NaN
111  ROUND TYPE    NaN  10/15/2016         18          18  ...    NaN

     Environment Unit of Sale Quality Condition Appearance  Storage Crop  \
0            NaN          NaN     NaN       NaN        NaN      NaN  NaN
1            NaN          NaN     NaN       NaN        NaN      NaN  NaN
2            NaN          NaN     NaN       NaN        NaN      NaN  NaN
3            NaN          NaN     NaN       NaN        NaN      NaN  NaN
4            NaN          NaN     NaN       NaN        NaN      NaN  NaN
..           ...          ...     ...       ...        ...      ...  ...
107          NaN          NaN     NaN       NaN        NaN      NaN  NaN
108          NaN          NaN     NaN       NaN        NaN      NaN  NaN
109          NaN          NaN     NaN       NaN        NaN      NaN  NaN
110          NaN          NaN     NaN       NaN        NaN      NaN  NaN
111          NaN          NaN     NaN       NaN        NaN      NaN  NaN

     Repack  Trans Mode
0         N         NaN
1         N         NaN
2         N         NaN
3         N         NaN
4         N         NaN
..      ...         ...
107       N         NaN
108       N         NaN
109       N         NaN
110       N         NaN
111       N         NaN

[112 rows x 25 columns]
   Commodity Name     City Name  Type               Package       Variety  \
0        PUMPKINS  PHILADELPHIA   NaN          24 inch bins   HOWDEN TYPE
1        PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
2        PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
3        PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
4        PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
5        PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
6        PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
7        PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
8        PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
9        PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
10       PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
11       PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
12       PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
13       PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
14       PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
15       PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
16       PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
17       PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
18       PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
19       PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
20       PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
21       PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
22       PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
23       PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
24       PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
25       PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
26       PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
27       PUMPKINS  PHILADELPHIA   NaN          36 inch bins   HOWDEN TYPE
28       PUMPKINS  PHILADELPHIA   NaN  1 1/9 bushel cartons      PIE TYPE
29       PUMPKINS  PHILADELPHIA   NaN  1 1/9 bushel cartons      PIE TYPE
30       PUMPKINS  PHILADELPHIA   NaN  1 1/9 bushel cartons      PIE TYPE
31       PUMPKINS  PHILADELPHIA   NaN  1 1/9 bushel cartons      PIE TYPE
32       PUMPKINS  PHILADELPHIA   NaN  1 1/9 bushel cartons      PIE TYPE
33       PUMPKINS  PHILADELPHIA   NaN  1 1/9 bushel cartons      PIE TYPE
34       PUMPKINS  PHILADELPHIA   NaN          24 inch bins      PIE TYPE
35       PUMPKINS  PHILADELPHIA   NaN          24 inch bins      PIE TYPE
36       PUMPKINS  PHILADELPHIA   NaN          24 inch bins      PIE TYPE
37       PUMPKINS  PHILADELPHIA   NaN          24 inch bins      PIE TYPE
38       PUMPKINS  PHILADELPHIA   NaN          24 inch bins      PIE TYPE
39       PUMPKINS  PHILADELPHIA   NaN          24 inch bins      PIE TYPE
40       PUMPKINS  PHILADELPHIA   NaN          24 inch bins      PIE TYPE
41       PUMPKINS  PHILADELPHIA   NaN          24 inch bins      PIE TYPE
42       PUMPKINS  PHILADELPHIA   NaN          24 inch bins      PIE TYPE
43       PUMPKINS  PHILADELPHIA   NaN          24 inch bins      PIE TYPE
44       PUMPKINS  PHILADELPHIA   NaN          24 inch bins  KNUCKLE HEAD
45       PUMPKINS  PHILADELPHIA   NaN    1/2 bushel cartons     MINIATURE
46       PUMPKINS  PHILADELPHIA   NaN    1/2 bushel cartons     MINIATURE
47       PUMPKINS  PHILADELPHIA   NaN    1/2 bushel cartons     MINIATURE
48       PUMPKINS  PHILADELPHIA   NaN    1/2 bushel cartons     MINIATURE
49       PUMPKINS  PHILADELPHIA   NaN    1/2 bushel cartons     MINIATURE
50       PUMPKINS  PHILADELPHIA   NaN    1/2 bushel cartons     MINIATURE
51       PUMPKINS  PHILADELPHIA   NaN    1/2 bushel cartons     MINIATURE
52       PUMPKINS  PHILADELPHIA   NaN    1/2 bushel cartons     MINIATURE
53       PUMPKINS  PHILADELPHIA   NaN    1/2 bushel cartons     MINIATURE
54       PUMPKINS  PHILADELPHIA   NaN    1/2 bushel cartons     MINIATURE
55       PUMPKINS  PHILADELPHIA   NaN    1/2 bushel cartons     MINIATURE
56       PUMPKINS  PHILADELPHIA   NaN    1/2 bushel cartons     MINIATURE

   Sub Variety  Grade        Date  Low Price  High Price  ...  Color  \
0          NaN    NaN  09/16/2017        140         150  ...    NaN
1          NaN    NaN  09/24/2016        150         150  ...    NaN
2          NaN    NaN  09/24/2016        150         150  ...    NaN
3          NaN    NaN  09/24/2016        150         160  ...    NaN
4          NaN    NaN  10/01/2016        140         140  ...    NaN
5          NaN    NaN  10/01/2016        140         140  ...    NaN
6          NaN    NaN  10/01/2016        120         120  ...    NaN
7          NaN    NaN  10/08/2016        140         155  ...    NaN
8          NaN    NaN  10/08/2016        120         120  ...    NaN
9          NaN    NaN  10/15/2016        120         125  ...    NaN
10         NaN    NaN  10/15/2016        100         125  ...    NaN
11         NaN    NaN  10/22/2016        130         140  ...    NaN
12         NaN    NaN  10/22/2016        120         120  ...    NaN
13         NaN    NaN  10/22/2016        130         140  ...    NaN
14         NaN    NaN  10/22/2016        100         120  ...    NaN
15         NaN    NaN  10/29/2016        130         140  ...    NaN
16         NaN    NaN  10/29/2016        120         120  ...    NaN
17         NaN    NaN  10/29/2016        130         140  ...    NaN
18         NaN    NaN  10/29/2016        100         120  ...    NaN
19         NaN    NaN  09/16/2017        120         120  ...    NaN
20         NaN    NaN  09/16/2017        120         150  ...    NaN
21         NaN    NaN  09/23/2017        140         140  ...    NaN
22         NaN    NaN  09/23/2017        150         150  ...    NaN
23         NaN    NaN  09/23/2017        120         150  ...    NaN
24         NaN    NaN  09/23/2017        140         150  ...    NaN
25         NaN    NaN  09/23/2017        140         150  ...    NaN
26         NaN    NaN  09/30/2017        140         140  ...    NaN
27         NaN    NaN  09/30/2017        140         140  ...    NaN
28         NaN    NaN  10/15/2016         12          14  ...    NaN
29         NaN    NaN  10/22/2016         12          12  ...    NaN
30         NaN    NaN  10/29/2016         12          12  ...    NaN
31         NaN    NaN  08/26/2017         18          20  ...    NaN
32         NaN    NaN  09/16/2017         18          18  ...    NaN
33         NaN    NaN  09/23/2017         18          22  ...    NaN
34         NaN    NaN  10/01/2016        250         250  ...    NaN
35         NaN    NaN  10/15/2016        140         140  ...    NaN
36         NaN    NaN  10/22/2016        140         150  ...    NaN
37         NaN    NaN  10/22/2016         75         100  ...    NaN
38         NaN    NaN  10/29/2016        140         150  ...    NaN
39         NaN    NaN  10/29/2016         75         100  ...    NaN
40         NaN    NaN  09/23/2017        180         180  ...    NaN
41         NaN    NaN  09/23/2017        140         140  ...    NaN
42         NaN    NaN  09/23/2017        180         180  ...    NaN
43         NaN    NaN  09/30/2017        140         140  ...    NaN
44         NaN    NaN  10/08/2016        210         210  ...    NaN
45   FLAT TYPE    NaN  09/24/2016         17          18  ...    NaN
46   FLAT TYPE    NaN  10/01/2016         18          18  ...    NaN
47   FLAT TYPE    NaN  10/01/2016         17          18  ...    NaN
48   FLAT TYPE    NaN  10/08/2016         15          15  ...    NaN
49   FLAT TYPE    NaN  10/15/2016         15          18  ...    NaN
50   FLAT TYPE    NaN  10/22/2016         16          18  ...    NaN
51   FLAT TYPE    NaN  10/29/2016         16          18  ...    NaN
52   FLAT TYPE    NaN  11/05/2016         16          18  ...    NaN
53   FLAT TYPE    NaN  08/26/2017         18          20  ...    NaN
54   FLAT TYPE    NaN  09/16/2017         16          16  ...    NaN
55   FLAT TYPE    NaN  09/23/2017         15          16  ...    NaN
56   FLAT TYPE    NaN  09/30/2017         15          18  ...    NaN

    Environment Unit of Sale  Quality Condition  Appearance  Storage Crop  \
0           NaN          NaN      NaN       NaN         NaN      NaN  NaN
1           NaN          NaN      NaN       NaN         NaN      NaN  NaN
2           NaN          NaN      NaN       NaN         NaN      NaN  NaN
3           NaN          NaN      NaN       NaN         NaN      NaN  NaN
4           NaN          NaN      NaN       NaN         NaN      NaN  NaN
5           NaN          NaN      NaN       NaN         NaN      NaN  NaN
6           NaN          NaN      NaN       NaN         NaN      NaN  NaN
7           NaN          NaN      NaN       NaN         NaN      NaN  NaN
8           NaN          NaN      NaN       NaN         NaN      NaN  NaN
9           NaN          NaN      NaN       NaN         NaN      NaN  NaN
10          NaN          NaN      NaN       NaN         NaN      NaN  NaN
11          NaN          NaN      NaN       NaN         NaN      NaN  NaN
12          NaN          NaN      NaN       NaN         NaN      NaN  NaN
13          NaN          NaN      NaN       NaN         NaN      NaN  NaN
14          NaN          NaN      NaN       NaN         NaN      NaN  NaN
15          NaN          NaN      NaN       NaN         NaN      NaN  NaN
16          NaN          NaN      NaN       NaN         NaN      NaN  NaN
17          NaN          NaN      NaN       NaN         NaN      NaN  NaN
18          NaN          NaN      NaN       NaN         NaN      NaN  NaN
19          NaN          NaN      NaN       NaN         NaN      NaN  NaN
20          NaN          NaN      NaN       NaN         NaN      NaN  NaN
21          NaN          NaN      NaN       NaN         NaN      NaN  NaN
22          NaN          NaN      NaN       NaN         NaN      NaN  NaN
23          NaN          NaN      NaN       NaN         NaN      NaN  NaN
24          NaN          NaN      NaN       NaN         NaN      NaN  NaN
25          NaN          NaN      NaN       NaN         NaN      NaN  NaN
26          NaN          NaN      NaN       NaN         NaN      NaN  NaN
27          NaN          NaN      NaN       NaN         NaN      NaN  NaN
28          NaN          NaN      NaN       NaN         NaN      NaN  NaN
29          NaN          NaN      NaN       NaN         NaN      NaN  NaN
30          NaN          NaN      NaN       NaN         NaN      NaN  NaN
31          NaN          NaN      NaN       NaN         NaN      NaN  NaN
32          NaN          NaN      NaN       NaN         NaN      NaN  NaN
33          NaN          NaN      NaN       NaN         NaN      NaN  NaN
34          NaN          NaN      NaN       NaN         NaN      NaN  NaN
35          NaN          NaN      NaN       NaN         NaN      NaN  NaN
36          NaN          NaN      NaN       NaN         NaN      NaN  NaN
37          NaN          NaN      NaN       NaN         NaN      NaN  NaN
38          NaN          NaN      NaN       NaN         NaN      NaN  NaN
39          NaN          NaN      NaN       NaN         NaN      NaN  NaN

## Clean Your Data

In the last lesson, we cleaned the data related to San Francisco. Pull up your notebook from the last lesson and use it as a reference to clean up these new dataframes.

In [62]:
# Clean your data here!
northeast_region["Repack"] = northeast_region["Repack"].replace({"N":False})
northeast_region.head(3)

# Fill the Missing Values in the Type Column
northeast_region["Type"] = northeast_region["Type"].fillna("Conventional")
northeast_region.head(3)

# drop Grade Column 
# northeast_region = northeast_region.drop("Grade", axis=1)
# northeast_region.shape

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Date,Low Price,High Price,Mostly Low,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,BALTIMORE,Conventional,24 inch bins,NaN,NaN,04/29/2017,270,280.0,270,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,NaN
1,PUMPKINS,BALTIMORE,Conventional,24 inch bins,NaN,NaN,05/06/2017,270,280.0,270,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,NaN
2,PUMPKINS,BALTIMORE,Conventional,24 inch bins,HOWDEN TYPE,NaN,09/24/2016,160,160.0,160,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN

## Combine Your Data

Now that you have four clean sets of data, combine all four into one dataframe that represents the entire Northeast region.

In [63]:
# Combine the four dataframes into one!
northeast_region = pd.concat([baltimore_df, boston_df, new_york_df, philadelphia_df], axis=0)
print(northeast_region.head(25))

   Commodity Name  City Name  Type       Package      Variety Sub Variety  \
0        PUMPKINS  BALTIMORE   NaN  24 inch bins          NaN         NaN
1        PUMPKINS  BALTIMORE   NaN  24 inch bins          NaN         NaN
2        PUMPKINS  BALTIMORE   NaN  24 inch bins  HOWDEN TYPE         NaN
3        PUMPKINS  BALTIMORE   NaN  24 inch bins  HOWDEN TYPE         NaN
4        PUMPKINS  BALTIMORE   NaN  24 inch bins  HOWDEN TYPE         NaN
5        PUMPKINS  BALTIMORE   NaN  24 inch bins  HOWDEN TYPE         NaN
6        PUMPKINS  BALTIMORE   NaN  36 inch bins  HOWDEN TYPE         NaN
7        PUMPKINS  BALTIMORE   NaN  36 inch bins  HOWDEN TYPE         NaN
8        PUMPKINS  BALTIMORE   NaN  36 inch bins  HOWDEN TYPE         NaN
9        PUMPKINS  BALTIMORE   NaN  36 inch bins  HOWDEN TYPE         NaN
10       PUMPKINS  BALTIMORE   NaN  36 inch bins  HOWDEN TYPE         NaN
11       PUMPKINS  BALTIMORE   NaN  36 inch bins  HOWDEN TYPE         NaN
12       PUMPKINS  BALTIMORE   NaN  36 inch bins  HOWDEN TYPE         NaN
13       PUMPKINS  BALTIMORE   NaN  36 inch bins  HOWDEN TYPE         NaN
14       PUMPKINS  BALTIMORE   NaN  36 inch bins  HOWDEN TYPE         NaN
15       PUMPKINS  BALTIMORE   NaN  36 inch bins  HOWDEN TYPE         NaN
16       PUMPKINS  BALTIMORE   NaN  36 inch bins  HOWDEN TYPE         NaN
17       PUMPKINS  BALTIMORE   NaN  36 inch bins  HOWDEN TYPE         NaN
18       PUMPKINS  BALTIMORE   NaN  36 inch bins  HOWDEN TYPE         NaN
19       PUMPKINS  BALTIMORE   NaN  36 inch bins  HOWDEN TYPE         NaN
20       PUMPKINS  BALTIMORE   NaN  36 inch bins  HOWDEN TYPE         NaN
21       PUMPKINS  BALTIMORE   NaN  36 inch bins  HOWDEN TYPE         NaN
22       PUMPKINS  BALTIMORE   NaN  36 inch bins  HOWDEN TYPE         NaN
23       PUMPKINS  BALTIMORE   NaN  36 inch bins  HOWDEN TYPE         NaN
24       PUMPKINS  BALTIMORE   NaN  36 inch bins  HOWDEN TYPE         NaN

    Grade        Date  Low Price  High Price  ...   Color  Environment  \
0     NaN  04/29/2017        270       280.0  ...     NaN          NaN
1     NaN  05/06/2017        270       280.0  ...     NaN          NaN
2     NaN  09/24/2016        160       160.0  ...     NaN          NaN
3     NaN  09/24/2016        160       160.0  ...     NaN          NaN
4     NaN  11/05/2016         90       100.0  ...     NaN          NaN
5     NaN  11/12/2016         90       100.0  ...     NaN          NaN
6     NaN  09/24/2016        160       170.0  ...     NaN          NaN
7     NaN  09/24/2016        160       160.0  ...     NaN          NaN
8     NaN  10/01/2016        160       170.0  ...     NaN          NaN
9     NaN  10/01/2016        160       160.0  ...     NaN          NaN
10    NaN  10/08/2016        160       170.0  ...     NaN          NaN
11    NaN  10/08/2016        160       160.0  ...     NaN          NaN
12    NaN  10/15/2016        150       160.0  ...     NaN          NaN
13    NaN  10/15/2016        150       170.0  ...     NaN          NaN
14    NaN  10/22/2016        150       160.0  ...     NaN          NaN
15    NaN  10/22/2016        140       160.0  ...     NaN          NaN
16    NaN  10/29/2016        100       160.0  ...     NaN          NaN
17    NaN  10/29/2016        130       160.0  ...     NaN          NaN
18    NaN  10/29/2016        130       130.0  ...     NaN          NaN
19    NaN  11/05/2016        120       130.0  ...     NaN          NaN
20    NaN  11/05/2016        100       130.0  ...     NaN          NaN
21    NaN  11/05/2016         90       100.0  ...     NaN          NaN
22    NaN  11/12/2016        100       120.0  ...     NaN          NaN
23    NaN  09/16/2017        160       160.0  ...  ORANGE          NaN
24    NaN  09/23/2017        160       160.0  ...  ORANGE          NaN

   Unit of Sale Quality Condition Appearance  Storage Crop  Repack  Trans Mode
0           NaN     NaN       NaN        NaN      NaN  NaN       E         NaN
1           NaN     NaN       NaN        NaN      NaN  NaN       E         NaN
2           NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
3           NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
4           NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
5           NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
6           NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
7           NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
8           NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
9           NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
10          NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
11          NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
12          NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
13          NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
14          NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
15          NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
16          NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
17          NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
18          NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
19          NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
20          NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
21          NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
22          NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
23          NaN     NaN       NaN        NaN      NaN  NaN       N         NaN
24          NaN     NaN       NaN        NaN      NaN  NaN       N         NaN

[25 rows x 25 columns]

## Answer Some Questions

Use `groupby()` and `agg()` to answer the following two questions:

1. What is the mean low and high prices for each type of **unit of sale** in the Northeast region? 
2. For each region, what is the average number of pumpkins per variety that came into terminal markets for the year?

In [67]:
# Put your code here to find the mean low and high prices in the Northeast region for each type of unit of sale.

unit_group = northeast_region.groupby("Unit of Sale")
print(unit_group.agg("mean", numeric_only=True))

              Type  Grade   Low Price  High Price  Mostly Low  Mostly High  \
Unit of Sale
EACH           NaN    NaN   47.916667   59.166667   47.916667    59.166667
PER BIN        NaN    NaN  185.845070  206.619718  193.521127   204.859155
SHELLACKED     NaN    NaN   16.000000   17.545455   16.000000    17.545455

              Environment  Quality  Condition  Appearance  Storage  Crop  \
Unit of Sale
EACH                  NaN      NaN        NaN         NaN      NaN   NaN
PER BIN               NaN      NaN        NaN         NaN      NaN   NaN
SHELLACKED            NaN      NaN        NaN         NaN      NaN   NaN

              Trans Mode
Unit of Sale
EACH                 NaN
PER BIN              NaN
SHELLACKED           NaN

In [71]:
# Put your code here to find the average number of pumpkins coming into terminal markets of each variety.
num_cities = len(northeast_region['City Name'].unique())
print(northeast_region['Variety'].value_counts()/num_cities)

Variety
HOWDEN TYPE                 56.00
PIE TYPE                    49.50
MINIATURE                   24.25
BIG MACK TYPE               13.75
CINDERELLA                   9.75
FAIRYTALE                    9.25
KNUCKLE HEAD                 2.25
BLUE TYPE                    1.75
MIXED HEIRLOOM VARIETIES     1.00
HOWDEN WHITE TYPE            0.50
Name: count, dtype: float64

## Bonus Mission

Try answering the same questions for the Midwest (Chicago, Detroit, and St. Louis) or the Southeast (Atlanta, Columbia, and Miami) regions.

In [70]:
# Try the bonus mission if you have time!